# Generated by Django 3.1.2 on 2020-10-01 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_deal_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='deal',
        ),
        migrations.DeleteModel(
            name='Deal',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
