# Generated by Django 3.1.2 on 2020-10-01 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_auto_20201001_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.deal')),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='deals',
            field=models.ManyToManyField(to='restaurants.Deal'),
        ),
    ]
