# Generated by Django 3.1.2 on 2020-10-01 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_auto_20201001_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='deal',
        ),
        migrations.AddField(
            model_name='deal',
            name='orders',
            field=models.ManyToManyField(to='restaurants.Order'),
        ),
    ]
