# Generated by Django 3.1.2 on 2020-10-01 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_auto_20201001_1737'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='User',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='orders',
        ),
        migrations.AddField(
            model_name='deal',
            name='users',
            field=models.ManyToManyField(to='restaurants.User'),
        ),
    ]
