# Generated by Django 3.1.2 on 2020-10-02 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_auto_20201001_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.deal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.user')),
            ],
        ),
    ]
