# Generated by Django 3.1.2 on 2020-10-02 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_auto_20201002_0341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='users',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='deals',
        ),
        migrations.AddField(
            model_name='deal',
            name='description',
            field=models.CharField(default='test description', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deal',
            name='img_url',
            field=models.CharField(default='random-img.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deal',
            name='new_price',
            field=models.FloatField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deal',
            name='original_price',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deal',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='restaurants.restaurant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deal',
            name='title',
            field=models.CharField(default='bad', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='restaurants.deal'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='restaurants.user'),
        ),
    ]
