# Generated by Django 3.1.2 on 2020-10-02 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_auto_20201002_0435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='name',
        ),
    ]
