# Generated by Django 3.1.2 on 2020-10-02 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='restaurants.deal'),
        ),
    ]
