# Generated by Django 3.1.2 on 2020-10-03 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0013_auto_20201003_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phonenumber',
            field=models.CharField(default='8583553939', max_length=15),
            preserve_default=False,
        ),
    ]
