# Generated by Django 3.1.2 on 2020-10-03 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0014_user_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='current_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deal',
            name='final_votes',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
    ]
