# Generated by Django 3.1.2 on 2020-10-03 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0015_auto_20201003_0452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='current_votes',
        ),
    ]
