# Generated by Django 3.1.2 on 2020-10-03 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0016_remove_deal_current_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='img_url',
            field=models.CharField(default='https://www.hokkai.com/wp-content/uploads/2019/05/1307-Sakesashimi.jpg', max_length=100),
            preserve_default=False,
        ),
    ]
